//TYPE
//ACCOUNT
export const NEW_ACCOUNT_NOT_PASSWORD = process.env.REACT_APP_NEW_ACCOUNT_NOT_PASSWORD
export const ENABLE_ACCOUNT = process.env.REACT_APP_ENABLE_ACCOUNT
export const FORGOT_PASSWORD_ACCOUNT = process.env.REACT_APP_FORGOT_PASSWORD_ACCOUNT
export const ACCOUNTS = process.env.REACT_APP_ACCOUNTS

//AUTH
export const LOGIN = process.env.REACT_APP_LOGIN
export const SIGNUP = process.env.REACT_APP_SIGUP
export const LOGOUT = process.env.REACT_APP_LOGOUT

//REGISTER
export const CREATE_NEW_REGISTER = process.env.REACT_APP_CREATE_NEW_REGISTER
export const SEARCH_REGISTER_EMAIL = process.env.REACT_APP_SEARCH_REGISTER_EMAIL

//SUPERVISOR
export const ALL_PROVINCE_PRICE = process.env.REACT_APP_ALL_PROVINCE_PRICE
export const PROVINCE_NOT_PRICE = process.env.REACT_APP_PROVINCE_NOT_PRICE
export const PROVINCE_WITH_PRICE = process.env.REACT_APP_PROVINCE_WITH_PRICE
export const UPDATE_PROVINCE_PRICE = process.env.REACT_APP_UPDATE_PROVINCE_PRICE


//-------------URL API-----------
//ACCOUNT
export const URL_NEW_ACCOUNT_NOT_PASSWORD = process.env.REACT_APP_URL_NEW_ACCOUNT_NOT_PASSWORD
export const URL_ENABLE_ACCOUNT = process.env.REACT_APP_URL_ENABLE_ACCOUNT
export const URL_FORGOT_PASSWORD_ACCOUNT = process.env.REACT_APP_URL_FORGOT_PASSWORD_ACCOUNT
export const URL_ACCOUNTS = process.env.REACT_APP_URL_ACCOUNTS

//AUTH
export const URL_LOGIN = process.env.REACT_APP_URL_LOGIN
export const URL_SIGNUP = process.env.REACT_APP_URL_SIGNUP

//REGISTER
export const URL_CREATE_NEW_REGISTER = process.env.REACT_APP_URL_CREATE_NEW_REGISTER
export const URL_SEARCH_REGISTER_EMAIL = process.env.REACT_APP_URL_SEARCH_REGISTER_EMAIL

//SUPERVISOR
export const URL_ALL_PROVINCE_PRICE = process.env.REACT_APP_URL_ALL_PROVINCE_PRICE
export const URL_PROVINCE_NOT_PRICE = process.env.REACT_APP_URL_PROVINCE_NOT_PRICE
export const URL_PROVINCE_WITH_PRICE = process.env.REACT_APP_URL_PROVINCE_WITH_PRICE
export const URL_UPDATE_PROVINCE_PRICE = process.env.REACT_APP_URL_UPDATE_PROVINCE_PRICE