//TYPE
export const LOGIN = process.env.REACT_APP_LOGIN
export const LOGOUT = process.env.REACT_APP_LOGOUT
export const SIGNUP = process.env.REACT_APP_SIGUP
export const SEARCH_REGISTER_EMAIL = process.env.REACT_APP_SEARCH_REGISTER_EMAIL
export const CREATE_NEW_REGISTER = process.env.REACT_APP_CREATE_NEW_REGISTER
export const FORGOT_PASSWORD = process.env.REACT_APP_FORGOT_PASSWORD

//URL API
export const URL_LOGIN = process.env.REACT_APP_URL_LOGIN
export const URL_SIGNUP = process.env.REACT_APP_URL_SIGNUP
export const URL_SEARCH_REGISTER_EMAIL = process.env.REACT_APP_URL_SEARCH_REGISTER_EMAIL
export const URL_CREATE_NEW_REGISTER = process.env.REACT_APP_URL_CREATE_NEW_REGISTER
export const URL_FORGOT_PASSWORD = process.env.REACT_APP_URL_FORGOT_PASSWORD