//TYPE
//AUTH
export const LOGIN = process.env.REACT_APP_LOGIN
export const SIGNUP = process.env.REACT_APP_SIGUP
export const LOGOUT = process.env.REACT_APP_LOGOUT

//REGISTER
export const FORGOT_PASSWORD = process.env.REACT_APP_FORGOT_PASSWORD
export const CREATE_NEW_REGISTER = process.env.REACT_APP_CREATE_NEW_REGISTER
export const SEARCH_REGISTER_EMAIL = process.env.REACT_APP_SEARCH_REGISTER_EMAIL

//SUPERVISOR
export const ALL_PROVINCE_PRICE = process.env.REACT_APP_ALL_PROVINCE_PRICE
export const PROVINCE_NOT_PRICE = process.env.REACT_APP_PROVINCE_NOT_PRICE
export const PROVINCE_WITH_PRICE = process.env.REACT_APP_PROVINCE_WITH_PRICE
export const UPDATE_PROVINCE_PRICE = process.env.REACT_APP_UPDATE_PROVINCE_PRICE

//-------------URL API-----------
//AUTH
export const URL_LOGIN = process.env.REACT_APP_URL_LOGIN
export const URL_SIGNUP = process.env.REACT_APP_URL_SIGNUP
export const URL_FORGOT_PASSWORD = process.env.REACT_APP_URL_FORGOT_PASSWORD

//REGISTER
export const URL_CREATE_NEW_REGISTER = process.env.REACT_APP_URL_CREATE_NEW_REGISTER
export const URL_SEARCH_REGISTER_EMAIL = process.env.REACT_APP_URL_SEARCH_REGISTER_EMAIL

//SUPERVISOR
export const URL_ALL_PROVINCE_PRICE = process.env.REACT_APP_URL_ALL_PROVINCE_PRICE
export const URL_PROVINCE_NOT_PRICE = process.env.REACT_APP_URL_PROVINCE_NOT_PRICE
export const URL_PROVINCE_WITH_PRICE = process.env.REACT_APP_URL_PROVINCE_WITH_PRICE
export const URL_UPDATE_PROVINCE_PRICE = process.env.REACT_APP_URL_UPDATE_PROVINCE_PRICE