export const nameGroup = [
  { group: "group_1" },
  { group: "group_2" },
  { group: "group_3" },
  { group: "group_4" },
];

export const column = [
  { name: "auto", group: "group_1" },
  { name: "remis", group: "group_1" },
  { name: "moto", group: "group_1" },
  { name: "fuel", group: "group_1" },
  { name: "parking", group: "group_1" },
  { name: "housing", group: "group_2" },
  { name: "breakfast", group: "group_2" },
  { name: "lunch", group: "group_2" },
  { name: "dinner", group: "group_2" },
  { name: "tip", group: "group_2" },
  { name: "bookstore", group: "group_3" },
  { name: "seamstress", group: "group_3" },
  { name: "encomienda", group: "group_3" },
  { name: "correo", group: "group_3" },
  { name: "supermarket", group: "group_3" },
  { name: "cleaning", group: "group_1" },
  { name: "other", group: "group_2" },
  { name: "previousBalance", group: "group_4" },
  { name: "advancePayment", group: "group_4" },
  { name: "reintegrationServicom", group: "group_4" },
  { name: "reintegrationUser", group: "group_4" },
  { name: "totalSpent", group: "group_4" },
];

export const props = {
  auto: null,
  remis: null,
  moto: null,
  fuel: null,
  parking: null,
  housing: null,
  breakfast: null,
  lunch: null,
  dinner: null,
  tip: null,
  bookstore: null,
  seamstress: null,
  encomienda: null,
  correo: null,
  supermarket: null,
  cleaning: null,
  other: null,
  previousBalance: null,
  advancePayment: null,
  reintegrationServicom: null,
  reintegrationUser: null,
  totalSpent: null,
};
