export const column = [
  { name: "auto", group: "group_1" },
  { name: "remis", group: "group_1" },
  { name: "moto", group: "group_1" },
  { name: "fuel", group: "group_1" },
  { name: "parking", group: "group_1" },
  { name: "housing", group: "group_2" },
  { name: "breakfast", group: "group_2" },
  { name: "lunch", group: "group_2"},
  { name: "dinner", group: "group_2" },
  { name: "tip", group: "group_2" },
  { name: "bookstore", group: "group_3" },
  { name: "seamstress", group: "group_3" },
  { name: "encomienda", group: "group_3" },
  { name: "correo", group: "group_3" },
  { name: "supermarket", group: "group_3" },
  { name: "cleaning", group: "group_4" },
  { name: "other", group: "group_4" },
  { name: "previousBalance", group: "group_4" },
  { name: "advancePayment", group: "group_4" },
  { name: "reintegrationServicom", group: "group_4" },
  { name: "reintegrationUser", group: "group_4" },
  { name: "totalSpent", group: "group_4" },
];

export const props = {
  auto: "",
  remis: "",
  moto: "",
  fuel: "",
  parking: "",
  housing: "",
  breakfast: "",
  lunch: "",
  dinner: "",
  tip: "",
  bookstore: "",
  seamstress: "",
  encomienda: "",
  correo: "",
  supermarket: "",
  cleaning: "",
  other: "",
  previousBalance: "",
  advancePayment: "",
  reintegrationServicom: "",
  reintegrationUser: "",
  totalSpent: "",
};
