export const ProvinceAndPrice = [
  { name: "Buenos_Aires", price: 0 },
  { name: "Catamarca", price: 0 },
  { name: "Chaco", price: 0 },
  { name: "Chubut", price: 0 },
  { name: "Córdoba", price: 0 },
  { name: "Corrientes", price: 0 },
  { name: "Entre_Ríos", price: 0 },
  { name: "Formosa", price: 0 },
  { name: "Jujuy", price: 0 },
  { name: "La_Pampa", price: 0 },
  { name: "La_Rioja", price: 0 },
  { name: "Mendoza", price: 0 },
  { name: "Misiones", price: 0 },
  { name: "Neuquén", price: 0 },
  { name: "Río_Negro", price: 0 },
  { name: "Salta", price: 0 },
  { name: "San_Juan", price: 0 },
  { name: "San_Luis", price: 0 },
  { name: "Santa_Cruz", price: 0 },
  { name: "Santa_Fe", price: 0 },
  { name: "Santiago_Del_Estero", price: 0 },
  { name: "Tierra_Del_Fuego", price: 0 },
  { name: "Tucumán", price: 0 },
];